version: '2.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  mongo:
    build: ./mongo
    expose:
      - 27017
    # healthcheck:
    #   test: echo 'db.stats().ok' | mongo 127.0.0.1:27017/assec --quiet
    #   retries: 3
    #   timeout: 10s
    #   interval: 1m30s
  graph:
    build: ./graph
    expose:
      - 3300
    depends_on:
      - mongo
    environment:
      - PORT=3300
    # mongo:
      #   condition: service_healthy
    # restart: always
  admin:
    build: ./admin
    expose:
      - 3200
    depends_on:
      - graph
    environment:
      - PORT=3200
  widget:
    build: ./widget
    expose:
      - 3100
    depends_on:
      - admin
    environment:
      - PORT=3100
  frontend:
    build: ./frontend
    expose:
      - 3000
    depends_on:
      - widget
    environment:
      - PORT=3000
