version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  mongo:
    build: ./mongo
    expose:
      - 27017
  graph:
    build: ./graph
    expose:
      - 3300
    depends_on:
      - "mongo"
    environment:
      - PORT=3300
  admin:
    build: ./admin
    expose:
      - 3200
    depends_on:
      - "graph"
    environment:
      - PORT=3200
  widget:
    build: ./widget
    expose:
      - 3100
    depends_on:
      - "admin"
    environment:
      - PORT=3100
  frontend:
    # les variables pour le build s'ajoute dans les fichier
    # - .env.staging
    build: ./frontend
    expose:
      - 3000
    depends_on:
      - "widget"
    environment:
      - PORT=3000
