version: '2.1'

services:
  mongo:
    volumes:
      # LOCAL
      # Le path /mongodb/db doit être défini dans les parametres
      # de l'application Docker Mac
      - /mongodb/db:/data/db
    env_file:
      - .env.loc
  graph:
    env_file:
      - .env.loc
    environment:
      - VIRTUAL_HOST=graph.docker.loc
  admin:
    env_file:
      - .env.loc
    environment:
      - VIRTUAL_HOST=admin.docker.loc
  widget:
    env_file:
      - .env.loc
    environment:
      - VIRTUAL_HOST=widget.docker.loc
  frontend:
    env_file:
      - .env.loc
    environment:
      - VIRTUAL_HOST=assec.docker.loc
