version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  graph:
    build: ./admin
    environment:
      - VIRTUAL_HOST=graph.iziges.fr
  admin:
    build: ./admin
    environment:
      - VIRTUAL_HOST=backend.iziges.fr
    depends_on:
      - graph
  frontend:
    build: ./frontend
    environment:
      - VIRTUAL_HOST=assec.iziges.fr
    depends_on:
      - graph
