version: '3'
services:
  web:
    build: ./nginx
    restart: always
    ports:
      - 80:8080
      - 81:8081
    depends_on:
      - admin
      - frontend
  admin:
    build: ./admin
    restart: always
    ports:
      - "3100"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000"
