version: '2'

# surcharge du fichier docker-compose
# le fichier docker-compose.prod est utilise pour la production
# sur le serveur VPS
services:
  mongo:
    # reference le container pour pouvoir y acceder facilement
    # en ligne de commande
    container_name: assec_mongodb_prod_container
    volumes:
      - /home/deploy/data/db:/data/db
      - /home/deploy/backups:/backups
    env_file:
      - .env.production
    environment:
      # - MONGO_INITDB_ROOT_USERNAME="admin"
      # - MONGO_INITDB_ROOT_PASSWORD="password"
  graph:
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=graph.iziges.fr
  admin:
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=admin.iziges.fr,aassec.beta.gouv.fr
  widget:
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=widget.iziges.fr,wassec.beta.gouv.fr
  frontend:
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=assec.iziges.fr,assec.beta.gouv.fr
