version: '2'

services:
  mongo:
    container_name: assec_mongodb_prod_container
    volumes:
      - /home/deploy/data/db:/data/db
      - /home/deploy/backups:/backups
    environment:
      - NODE_ENV=production
      # - MONGO_INITDB_ROOT_USERNAME="admin"
      # - MONGO_INITDB_ROOT_PASSWORD="password"
  graph:
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=graph.iziges.fr
  admin:
    # les variables pour le build s'ajoute dans les fichier
    # - .env.build.production
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=admin.iziges.fr,aassec.beta.gouv.fr
  widget:
    # les variables pour le build s'ajoute dans les fichier
    # - .env.build.production
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=widget.iziges.fr,wassec.beta.gouv.fr
  frontend:
    # les variables pour le build s'ajoute dans les fichier
    # - .env.build.production
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=assec.iziges.fr,assec.beta.gouv.fr
