version: '3'
services:
  web:
    build: ./nginx
    restart: always
    ports:
      - 80:8080
      - 81:8081
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000"
  admin:
    build: ./admin
    restart: always
    ports:
      - "3100"
  graph:
    build: ./frontend
    restart: always
    ports:
      - "3100"
