version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  graph:
    build: ./graph
    environment:
      - VIRTUAL_HOST=graph.docker.loc
  admin:
    build: ./admin
    environment:
      - VIRTUAL_HOST=admin.docker.loc
  frontend:
    build: ./frontend
    environment:
      - VIRTUAL_HOST=docker.loc
