version: '2.1'

services:
  mongo:
    env_file:
      - .env.local
    volumes:
      # permet d'acceder aux fichiers de backup de la BDD eg: departments.json
      - ./tmp:/tmp/backups
  graph:
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=graph.docker.loc
  admin:
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=admin.docker.loc
  widget:
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=widget.docker.loc
  frontend:
    env_file:
      - .env.local
    environment:
      - VIRTUAL_HOST=assec.docker.loc
