#!/bin/sh

# Install
# ---
# yarn add --dev prettier-eslint-cli prettier-eslint husky
# {
#  ...
#  "precommit": "sh ./.scripts/hooks/pre-commit"
# }
#
# Workflow (used with atom-prettier)
# ---
# ESLint -> Prettier-ESLint
#
jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.js" "*.jsx" | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

for file in $jsfiles
do
  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
    exit 1 # exit with failure status
  fi
done

# Prettify all staged .js files
echo "$jsfiles" | xargs ./node_modules/.bin/prettier-eslint --write
echo "$jsfiles" | xargs git add

exit 0
s
