#!/bin/bash

CURRENT=$(git ls-files -s ./graph | git hash-object --stdin)
SAVED=$(cat ./.hashs/graph)
if [ "$CURRENT" == "$SAVED" ]; then
  echo "is equal"
fi;

CURRENT=$(git ls-files -s ./frontend | git hash-object --stdin)
SAVED=$(cat ./.hashs/frontend)
if [ "$CURRENT" == "$SAVED" ]; then
  echo "is equal"
fi;
