#!/bin/bash

echo "┌───────────────────────────────────────────────────────┐"
echo "│                                                       │"
echo "│                GIT ENSURE CLEAN SCRIPT                │"
echo "│                                                       │"
echo "└───────────────────────────────────────────────────────┘"
echo
echo "$(tput bold)Start checking git status$(tput sgr0)"

# Check if git status is clean
GIT_STATUS=$(git status --porcelain)
if [ -n "$GIT_STATUS" ]; then
  echo "$(tput setaf 136)$(tput bold)❌  Git repository is dirty!, Please commit any changes before proceed$(tput sgr0)"
  echo
  exit 1
fi
