#!/bin/bash

# --------------------------------
#
# Genere une sortie statique de toutes les applications
# Pour une intégration à la branche gh-pages
#
# --------------------------------

(
  cd frontend
  yarn export
)
