#!/bin/bash

# --------------------------------
#
# Genere une sortie statique de toutes les applications
# Pour une intégration à la branche gh-pages
#
# --------------------------------

#yarn install
yarn sass
mkdir -p dist

(
  cd frontend
  yarn export
  cd dist
  touch .nojekyll
  cd ..
  cp -r ./dist/* ./../dist/
)
