#!/bin/bash

# --------------------------------
#
# Ce script est a utilisé uniquement avant le lancement de `yarn dev`
# Si les fichiers CSS ne sont pas déjà compilés
# et qu'ils sont manquant à la première installation de l'application
#
# Usage
# ---
# $ sh ./.scripts/yarn-sass
#
# --------------------------------

# compilation du CSS pour le Widget
(
  cd widget
  ./node_modules/.bin/node-sass -r src/scss/styles.scss src/styles.css --output-style compressed
)

# compilation du CSS pour le Widget
(
  cd admin
  ./node_modules/.bin/node-sass -r src/scss/styles.scss src/styles.css --output-style compressed
)
