#!/bin/bash

echo '------------------------------'
echo ''
echo 'Building Frontend Package'
echo ''
echo '------------------------------'
(
  cd ./frontend
  ./node_modules/.bin/node-sass -r ./src/scss/styles.scss ./src/styles.css --output-style compressed
  yarn build
)

echo '------------------------------'
echo ''
echo 'Building Admin Package'
echo ''
echo '------------------------------'
(
  cd ./admin
  ./node_modules/.bin/node-sass -r ./src/scss/styles.scss ./src/styles.css --output-style compressed
  yarn build
)
