#!/bin/bash

# ------------------------
#
# Description
# ---
# Cleanup de toutes les dependances des sous projets
# Les sous projets sont definis dans ./package.json { workspaces: [...] }
#
# Usage
# ---
# $ yarn cleanup
#
# ------------------------

# recupere les sous projets definis dans le main ./package.json
WORKSPACES=$(
  node -pe 'JSON.parse(process.argv[1]).workspaces.join(" ")' "$(cat package.json)"
)

function deleteFile () {
  if [ -f $1 ]; then
    echo "Deleting $1"
    rm "$1"
  fi
}

function deleteModules () {
  if [ -d $1 ]; then
    echo "Deleting $1"
    rm -rf "$1"
  fi
}

# ---- SUB PROJECTS ----
# iterate to workspaces
for FOLDER in $WORKSPACES
do
  # delete node_modules folder
  deleteModules "./$FOLDER/node_modules"
  # delete yarn error log file
  deleteFile "./$FOLDER/yarn-error.log"
  # delete yarn lock file
  deleteFile "./$FOLDER/yarn.lock"
  deleteFile "./$FOLDER/package-lock.json"
done

# ---- MAIN ----
# delete node_modules folder
deleteModules "./node_modules"
# delete yarn error log file
# delete yarn error log file
deleteFile "./yarn-error.log"
# delete yarn lock file
deleteFile "./yarn.lock"
deleteFile "./package-lock.json"

# install with yarn
yarn install

# ------------------------------------
# !!! NPM audit will be available soon
# https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905
#
# create a new package.lock file
# npm i --package-lock-only
# check for vulnerable packages
# npm audit
#

exit 0
